baseURL = "https://programmador.com"
theme = "risotto"
title = "ieg archive"
author = "Ivan Eduardo Guerra"
copyright = "All rights Reserved, Ivan Eduardo Guerra."
enableRobotsTXT = true
googleAnalytics = "G-XEENY573SL"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
sectionPagesMenu = "main"

[pagination]
pagerSize = 3

[params]
noindex = false

  [params.theme]
  palette = "windows-95"
  
  [params.about]
  title = "ieg archive"
  description = ""
  logo_image = "favicon.ico"
  
  [[params.socialLinks]]
  icon = "fa-brands fa-github"
  title = "GitHub"
  url = "https://github.com/ivan-guerra"
  
  [[params.socialLinks]]
  icon = "fa-solid fa-envelope"
  title = "Email"
  url = "mailto:ivan.eduardo.guerra@gmail.com"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    weight = 12
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 15

[taxonomies]
category = "categories"
tag = "tags"

# Enable Table of Contents in posts
[cascade]
toc = true

[markup.goldmark.renderer]
unsafe = true

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel   = 4
    ordered    = true

[privacy]
  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.x]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true
