[build.environment]
  HUGO_VERSION = "0.152.2"
  DART_SASS_VERSION = "1.93.3"
  NODE_VERSION = "25.1.0"
  TZ = "America/New_York"

[build]
  publish = "public"
  # See https://answers.netlify.com/t/hugo-builds-support-dart-sass/36531/14
  command = """\
    curl -LJO https://github.com/sass/dart-sass/releases/download/${DART_SASS_VERSION}/dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz && \
    tar -xf dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz && \
    rm dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz && \
    export PATH=/opt/build/repo/dart-sass:$PATH && \
    hugo --minify
    """

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = "404"
